### ISSUE TITLE
slides: feedback

### ISSUE THREAD

**Issue by michaelsevilla** [michaelsevilla/parsplice-ml-popper#54]

**Comment by jlefevre** [comment]
Slide7, left graph shows the ratio of gets:puts, which is non-linear.   But this ratio is also not evenly distributed, there is a heavy skew (with a particular pattern a rolling/increasing key range), toward a subset of keys are highly accessed. 

Slide 7.  You can probably remove the red notes "Eventually... and "Idea:...".if you want, these make the graphs look a little too busy to me.

Slide 15 seems to show the goal of minimizing the cache usage for key access (due to this app's key access pattern) so that mem resources are available for other things.  This is better than LRU because...

**Comment by yzhan298** [comment]
on page 7, you can place the images on two pages.

**Comment by reza-nasirigerdeh** [comment]
1) It is better to have Outline slide immediately after the Title slide so that you can talk about the material your are going to cover in the presentation by showing the Outline slide.

2) You had a figure showing the a set of workers and each worker have a in-memory database and in-disk database.  Next, you talked about the number of cores used in the simulations. I think you should clarify that:
The workers are running at the same or separate physical machines?
32 cores are the number of cores in a single machine or is it the total of cores of all physical machines?
Is all simulations are done in a single or multiple physical machines?

3) In slide 7, the left-hand figure
    The title of the y axis is (# of operations) but for the bar associated with put operation, you show (number of keys). I think it is confusing and it is better to use (# of operations) for the bar related to the put operation too.
4) In slide 7, right-hand figure
  The titles of the y axes are at the bottom of the figure. I think (as Jeff said) you should put the titles next to the y axes.
5) In slide 7, why don't use "Throughput" instead of "Thruput"?
6) In slide 13, two bars have the same title (100 keys). You should change them to make it clear which one is related to which method.
7) Slide numbers can be bigger and in bold font. Moreover, try to move them a little bit down to separate it from the LANL logo :)

**Comment by michaelsevilla** [comment]
Thanks, everyone!
